server:
  port: 8888

spring:
  application:
    name: zookeeper-client
  cloud:
    zookeeper:
      connect-string: 10.222.84.227:2181,10.222.84.228:2181,10.222.84.229:2181
      config:
        enabled: true
        #当前项目配置中心路径
        root: jrbdp
        #配置中心根路径
        defaultContext: datadevs-workspace
        profileSeparator: "-"
        watcher:
          enabled: true
      discovery:
        enabled: true
        register: false
        root: server-register

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://172.25.4.211:3306/jrbdp_metadata?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: m_jrbdp_metadata
    password: 28djyT
    name: nebulae
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j,config
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet.login-username: nebulae
      stat-view-servlet.login-password: nebulae
      aop-patterns: com.jd.nebulae.services.service.impl.*
