server:
  port: 8888

spring:
  application:
    name: zookeeper-client
  cloud:
    zookeeper:
      connect-string: 10.222.84.227:2181,10.222.84.228:2181,10.222.84.229:2181
      config:
        enabled: true
        #当前项目配置中心路径
        root: jrbdp
        #配置中心根路径
        defaultContext: datadevs-workspace
        profileSeparator: "-"
        watcher:
          enabled: true
      discovery:
        enabled: true
        register: false
        root: server-register
